### ISSUE TITLE
/altinitystablebuilds/stablequickstartguide/docker-install/

### ISSUE THREAD

**Issue by vadimtk** [Altinity/documentationIssues#14]
When I use docker-compose.yaml from documentation, I get

```
docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yaml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yaml", line 4, column 5
```

**Comment by johnhummelAltinity** [comment]
I'm making an update now, but this should work:

```
version: '3'

services:
  clickhouse_server:
      image: altinity/clickhouse-server:21.8.10.1.altinitystable
      ports:
      - "8123:8123"
      volumes:
      - ./clickhouse_database:/var/lib/clickhouse
      networks:
          - clickhouse_network

networks:
  clickhouse_network:
      driver: bridge
      ipam:
          config:
              - subnet: 10.222.1.0/24
```

And then run with:

```bash
docker compose up -d
docker compose exec clickhouse_server clickhouse-client
```

Let me know if there are issues - should be a happier place now.
