### ISSUE TITLE
/clickhouseonkubernetes/kubernetesquickstartguide/quickpersistentstorage/

### ISSUE THREAD

**Issue by hodgesrm** [Altinity/documentationIssues#16]
I get the following error when I try to run the sample05.yaml with storage against Google Kubernetes Engine (GKE) version 1.20. 

```
kubectl apply -f docs.yaml
error: error validating "docs.yaml": error validating data: [ValidationError(ClickHouseInstallation.spec.defaults): unknown field "deployment" in com.altinity.clickhouse.v1.ClickHouseInstallation.spec.defaults, ValidationError(ClickHouseInstallation.spec.templates.podTemplates[0]): unknown field "containers" in com.altinity.clickhouse.v1.ClickHouseInstallation.spec.templates.podTemplates, ValidationError(ClickHouseInstallation.spec.templates.volumeClaimTemplates[0]): unknown field "persistentVolumeClaim" in com.altinity.clickhouse.v1.ClickHouseInstallation.spec.templates.volumeClaimTemplates]; if you choose to ignore these errors, turn validation off with --validate=false
```

I am running v0.16.1 of the operator, which I installed using the instructions on docs.altinity.com.  To get things to work I had to change the CRD as follows: 
```

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "demo-01"
spec:
  configuration:
    zookeeper:
        nodes:
        - host: zookeeper.zoo1ns
          port: 2181
    clusters:
      - name: "demo-01"
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:latest
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
